# Copyright (c) 2016 Carnegie Mellon University.
# Copyright (c) 2011 The LevelDB Authors.
# ---------------------------------------
# All rights reserved.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file. See the AUTHORS file for names of contributors.

#-----------------------------------------------
# Uncomment exactly one of the lines labeled (A), (B), and (C) below
# to switch between compilation modes.

# (A) Production use (optimized mode)
OPT ?= -O2 -DNDEBUG
# (B) Debug mode, w/ full line-level debugging symbols
# OPT ?= -g2
# (C) Profiling mode: opt, but w/debugging symbols
# OPT ?= -O2 -g2 -DNDEBUG
#-----------------------------------------------

# detect what platform we're building on
$(shell CC="$(CC)" CXX="$(CXX)" TARGET_OS="$(TARGET_OS)" \
    ./build_detect_platform build_config.mk ./)
# this file is generated by the previous line to set build flags and sources
include build_config.mk

TESTS = \
        gigaplus_test

# Put the object files in a subdirectory, but the application at the top of the object dir.
PROGNAMES := $(notdir $(TESTS))

CFLAGS += -I./external/pdlfs-common/include -I./include $(PLATFORM_CCFLAGS) $(OPT)
CXXFLAGS += -I./external/pdlfs-common/include -I./include $(PLATFORM_CXXFLAGS) $(OPT)

LDFLAGS += $(PLATFORM_LDFLAGS)
LIBS += $(PLATFORM_LIBS)

OUTDIR=build

STATIC_OUTDIR=out-static

STATIC_PROGRAMS := $(addprefix $(STATIC_OUTDIR)/, $(PROGNAMES))

TESTUTIL := $(STATIC_OUTDIR)/external/pdlfs-common/src/testutil.o
TESTHARNESS := $(STATIC_OUTDIR)/external/pdlfs-common/src/testharness.o $(TESTUTIL)

STATIC_EXT_LIBOBJECTS := $(addprefix $(STATIC_OUTDIR)/, $(EXT_SOURCES:.cc=.o))
STATIC_LIBOBJECTS := $(addprefix $(STATIC_OUTDIR)/, $(SOURCES:.cc=.o))

STATIC_TESTOBJS := $(addprefix $(STATIC_OUTDIR)/, $(addsuffix .o, $(TESTS)))
STATIC_ALLOBJS := $(STATIC_LIBOBJECTS) $(STATIC_EXT_LIBOBJECTS) $(STATIC_TESTOBJS) $(TESTHARNESS)

SHARED_OUTDIR=out-shared

SHARED_EXT_LIBOBJECTS := $(addprefix $(SHARED_OUTDIR)/, $(EXT_SOURCES:.cc=.o))
SHARED_LIBOBJECTS := $(addprefix $(SHARED_OUTDIR)/, $(SOURCES:.cc=.o))

SHARED_ALLOBJS := $(SHARED_LIBOBJECTS) $(SHARED_EXT_LIBOBJECTS)

ALL = \
        $(STATIC_OUTDIR)/libpdlfs-common.a \
        $(SHARED_OUTDIR)/libpdlfs-common.$(PLATFORM_SHARED_EXT) \
	$(STATIC_OUTDIR)/libdeltafs.a \
	$(SHARED_OUTDIR)/libdeltafs.$(PLATFORM_SHARED_EXT)

default: all

all: $(ALL)
	mkdir -p $(OUTDIR)
	cd $(OUTDIR) && ln -fs ../$(STATIC_OUTDIR)/*.a .
	cd $(OUTDIR) && ln -fs ../$(SHARED_OUTDIR)/*.$(PLATFORM_SHARED_EXT) .

check: $(STATIC_PROGRAMS)
	for t in $(notdir $(TESTS)); do echo "***** Running $$t"; $(STATIC_OUTDIR)/$$t || exit 1; done

clean:
	-rm -rf $(OUTDIR) $(STATIC_OUTDIR) $(SHARED_OUTDIR)
	-rm -f build_config.mk

$(STATIC_OUTDIR):
	mkdir -p $@

$(STATIC_OUTDIR)/external/pdlfs-common/src: | $(STATIC_OUTDIR)
	mkdir -p $@

$(STATIC_OUTDIR)/external/pdlfs-common/src/leveldb: | $(STATIC_OUTDIR)
	mkdir -p $@

$(STATIC_OUTDIR)/external/pdlfs-common/src/leveldb/db: | $(STATIC_OUTDIR)
	mkdir -p $@

$(STATIC_OUTDIR)/external/pdlfs-common/modules/rados: | $(STATIC_OUTDIR)
	mkdir -p $@

$(STATIC_OUTDIR)/src: | $(STATIC_OUTDIR)
	mkdir -p $@

.PHONY: STATIC_OBJDIRS
STATIC_OBJDIRS: \
        $(STATIC_OUTDIR)/external/pdlfs-common/src \
	$(STATIC_OUTDIR)/external/pdlfs-common/src/leveldb \
	$(STATIC_OUTDIR)/external/pdlfs-common/src/leveldb/db \
	$(STATIC_OUTDIR)/external/pdlfs-common/modules/rados \
        $(STATIC_OUTDIR)/src

$(STATIC_ALLOBJS): | STATIC_OBJDIRS

$(SHARED_OUTDIR):
	mkdir -p $@

$(SHARED_OUTDIR)/external/pdlfs-common/src: | $(SHARED_OUTDIR)
	mkdir -p $@

$(SHARED_OUTDIR)/external/pdlfs-common/src/leveldb: | $(SHARED_OUTDIR)
	mkdir -p $@

$(SHARED_OUTDIR)/external/pdlfs-common/src/leveldb/db: | $(SHARED_OUTDIR)
	mkdir -p $@

$(SHARED_OUTDIR)/external/pdlfs-common/modules/rados: | $(SHARED_OUTDIR)
	mkdir -p $@

$(SHARED_OUTDIR)/src: | $(SHARED_OUTDIR)
	mkdir -p $@

.PHONY: STHARED_OBJDIRS
SHARED_OBJDIRS: \
        $(SHARED_OUTDIR)/external/pdlfs-common/src \
	$(SHARED_OUTDIR)/external/pdlfs-common/src/leveldb \
	$(SHARED_OUTDIR)/external/pdlfs-common/src/leveldb/db \
	$(SHARED_OUTDIR)/external/pdlfs-common/modules/rados \
        $(SHARED_OUTDIR)/src

$(SHARED_ALLOBJS): | SHARED_OBJDIRS

$(STATIC_OUTDIR)/libpdlfs-common.a:$(STATIC_EXT_LIBOBJECTS)
	rm -f $@
	$(AR) -rs $@ $(STATIC_EXT_LIBOBJECTS)

$(SHARED_OUTDIR)/libpdlfs-common.$(PLATFORM_SHARED_EXT): $(SHARED_EXT_LIBOBJECTS)
	$(CXX) $(LDFLAGS) $(PLATFORM_SHARED_LDFLAGS)libpdlfs-common.$(PLATFORM_SHARED_EXT) $(SHARED_EXT_LIBOBJECTS) \
	        -o $(SHARED_OUTDIR)/libpdlfs-common.$(PLATFORM_SHARED_EXT) $(LIBS)

$(STATIC_OUTDIR)/libdeltafs.a:$(STATIC_LIBOBJECTS)
	rm -f $@
	$(AR) -rs $@ $(STATIC_LIBOBJECTS)

$(SHARED_OUTDIR)/libdeltafs.$(PLATFORM_SHARED_EXT): $(SHARED_LIBOBJECTS)
	$(CXX) $(LDFLAGS) $(PLATFORM_SHARED_LDFLAGS)libdeltafs.$(PLATFORM_SHARED_EXT) $(SHARED_LIBOBJECTS) \
	        -o $(SHARED_OUTDIR)/libdeltafs.$(PLATFORM_SHARED_EXT) $(LIBS)

$(STATIC_OUTDIR)/gigaplus_test:src/gigaplus_test.cc $(STATIC_LIBOBJECTS) $(STATIC_EXT_LIBOBJECTS) $(TESTHARNESS)
	$(CXX) $(LDFLAGS) $(CXXFLAGS) src/gigaplus_test.cc $(STATIC_LIBOBJECTS) $(STATIC_EXT_LIBOBJECTS) $(TESTHARNESS) -o $@ $(LIBS)

$(STATIC_OUTDIR)/%.o: %.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(STATIC_OUTDIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

$(SHARED_OUTDIR)/%.o: %.cc
	$(CXX) $(CXXFLAGS) $(PLATFORM_SHARED_CFLAGS) -c $< -o $@

$(SHARED_OUTDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PLATFORM_SHARED_CFLAGS) -c $< -o $@
